sonata_admin:
    security:
        handler: App\Application\Sonata\UserBundle\Security\CustomRoleSecurityHandler # sonata.admin.security.handler.role
        information:
            LIST: LIST
            CREATE: CREATE
            EDIT: EDIT
            DELETE: DELETE
            EXPORT: EXPORT

    options:
        confirm_exit: false
    title: Portail Kids & Family
    title_logo: /img/com-lm-kf.png
    templates:
        # default global templates
        layout:  "bundles/SonataAdminBundle/layout.html.twig"
        edit:    "admin/core_custom/base_edit.html.twig"
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: gogo.block.recent_elements, settings: { title: 'Dernières validation collaboratives', filterStatus: 2, class: box-success}}
            - { position: right, type: gogo.block.recent_elements, settings: { title: 'Derniers refus collaboratifs', filterStatus: -3 , class: box-danger}}
            - { position: top, class: col-md-12, type: gogo.block.service.monitoring}
            - { position: top, class: col-md-12, type: gogo.block.service.charts}
        groups:
            Contenus:
                icon: <i class='fa fa-file-text'></i>
            data:
                label: "Données / Import"
                icon: <i class='fa fa-database'></i>
            custom:
                label: Personnalisation
                icon: <i class='fa fa-paint-brush'></i>
            pages:
                label: Pages Additionelles
                icon: <i class='fa fa-bookmark'></i>
            emailing:
                label: Mails / Newsletter
                icon: <i class='fa fa-envelope'></i>
            other_config:
                label: Autre Configuration
                icon: <i class='fa fa-cogs'></i>
            sonata_user:
                label: Utilisateurs
                icon: <i class='fa fa-users'></i>
            saas:
                label: Ferme de Carto
                icon: <i class='fa fa-cogs saas-menu'></i>